config/routes.rb
AchievementUnlocked::Application.routes.draw do
  resources :users do
    resources :goals, only: [:new, :create]
  end
  resource :session, only: [:new, :create, :destroy]
  resources :goals, except: [:new, :create]
  resources :comments, only: [:create]

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :body, presence: true
  belongs_to :commentable, polymorphic: true
  belongs_to :author, class_name: "User"
end

app/models/concerns/commentable.rb
module Commentable
  extend ActiveSupport::Concern

  included do
    has_many :comments, as: :commentable
  end

end

app/models/goal.rb
class Goal < ActiveRecord::Base
  validates :title, :user_id, presence: true

  belongs_to :user, inverse_of: :goals
  include Commentable
end

app/models/user.rb
class User < ActiveRecord::Base
  include Commentable

  validates :username, :password_digest, :session_token, presence: true

  has_many :goals, inverse_of: :user, dependent: :destroy

  has_many(
    :authored_comments,
    class_name: "Comment",
    foreign_key: :author_id,
    inverse_of: :author
  )

  after_initialize :ensure_session_token

  def self.find_by_credentials(username, password)
    @user = User.find_by_username(username)
    @user && @user.is_password?(password) ? @user : nil
  end

  attr_reader :password

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
    self.save!
    self.session_token
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
  helper_method :current_user

  def login!(user)
    session[:session_token] = user.reset_session_token!
  end

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def require_logged_in
    redirect_to new_session_url unless current_user
  end

  def logout!
    current_user.reset_session_token!
    session[:session_token] = nil
  end



end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = current_user.authored_comments.new(comment_params)

    flash[:errors] = @comment.errors.full_messages unless @comment.save
    redirect_to @comment.commentable_type.constantize.find(@comment.commentable_id)
  end

  private
  def comment_params
    params.require(:comment).permit(:body, :commentable_id, :commentable_type)
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :require_logged_in
  before_action :require_owner, only: [:edit, :update, :destroy]
  def new
  end

  def create
    @goal = current_user.goals.new(goal_params)
    if @goal.save
      redirect_to @goal
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :new
    end
  end

  def show
    @goal = Goal.find(params[:id])
    render :show
  end

  def edit
    @goal = current_user.goals.find(params[:id])
    render :edit
  end

  def update
    @goal = current_user.goals.find(params[:id])

    if @goal.update(goal_params)
      redirect_to @goal
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :new
    end
  end

  def destroy
    @goal = current_user.goals.find(params[:id])
    @goal.destroy!
    redirect_to user_url(current_user)
  end

  private
  def goal_params
    params.require(:goal)
      .permit(:title, :description, :private_goal, :completed)
  end

  def require_owner
    @goal = Goal.find(params[:id])
    unless current_user == @goal.user
      flash[:errors] = "Can't touch this"
      redirect_to goal_url(@goal)
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    username = params[:user][:username]
    password = params[:user][:password]
    @user = User.find_by_credentials(username, password)

    if @user
      login!(@user)
      redirect_to users_url
    else
      render :new
    end
  end

  def destroy
    logout!
    redirect_to users_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_logged_in, only: [:index, :show]

  def new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login!(@user)
      redirect_to users_url
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end


  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<form action="<%= comments_url %>" method="POST">
  <label for="Comment">Comment</label>
  <textarea id="Comment" name="comment[body]"></textarea>
  <input type="hidden"
    name="comment[commentable_type]" value="<%= subject.class %>">
  <input type="hidden"
    name="comment[commentable_id]" value="<%= subject.id %>">
  <button>Add Comment</button>
</form>

app/views/goals/edit.html.erb
<h1>Edit Goal</h1>

<form action="<%= goal_url(@goal) %>" method="POST">
  <input type="hidden" name="_method" value="PATCH">
  <label for="goal_title">Title</label>
  <input
    type="text"
    id="goal_title"
    name="goal[title]"
    value="<%= @goal.title %>">
  <br>
  <label for="goal_description">Description</label>
  <textarea
    id="goal_description"
    name="goal[description]"><%= @goal.description %></textarea>
  <br>
  Private or Public?
  <br>
  <input
    type="radio"
    id="private"
    name="goal[private_goal]"
    value="t"
  <%= "checked" if @goal.private_goal %>>
  <label for="private">Private</label>
  <br>
  <input type="radio"
    id="public"
    name="goal[private_goal]"
    value="f"
  <%= "checked" unless @goal.private_goal %>>
  <label for="public">Public</label>
  <br>
  <input
    type="checkbox"
    name="goal[completed]"
    id="completed"
    <%= "checked" if @goal.completed %>>
    <label for="completed">Completed?</label>
    <br>

  <button>Update Goal</button>
</form>

app/views/goals/new.html.erb
<h1>Create a Goal</h1>

<form action="<%= user_goals_url(current_user) %>" method="POST">
  <label for="goal_title">Title</label>
  <input type="text" id="goal_title" name="goal[title]">
  <br>
  <label for="goal_description">Description</label>
  <textarea id="goal_description" name="goal[description]"></textarea>
  <br>
  <button>Create Goal</button>
</form>

app/views/goals/show.html.erb
<h1><%= @goal.title %><%= "- COMPLETE!" if @goal.completed %></h1>
<p>
  <%= @goal.description %>
</p>
<%= @goal.private_goal ? "Private" : "Public" %><br>
<% if current_user.id == @goal.user_id %>
<p>
  <a href="<%= edit_goal_url(@goal) %>">Edit Goal</a><br>
</p>
  <form action="<%= goal_url(@goal) %>" method="POST">
    <input type="hidden" name="_method" value="DELETE">
    <button>Delete Goal</button>
  </form>
<% end %>

<br>
<%= render "comments/form", subject: @goal %>
<br>

<% @goal.comments.try(:each) do |comment| %>
  <%= comment.body %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AchievementUnlocked</title>
   <%= csrf_meta_tags %>
</head>
<body>
<% if current_user %>
  <form action="<%= session_url %>" method="POST">
    <input type="hidden" name="_method" value="DELETE">
    <button>Log out</button>
  </form>
  <%= current_user.username %>
<% end %>

<% flash[:errors].try(:each) do |error| %>
  <%= error %><br>
<% end %>


<%= yield %>

</body>
</html>

app/views/users/index.html.erb
<h1>Welcome</h1>
<p>
  <% User.all.each do |user| %>
    <%= user.username %><br>
  <% end %>
</p>

app/views/users/new.html.erb
<h1>Sign up</h1>

<form action="<%= users_url %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label for="user_username">username</label>
  <input type="text" id="user_username" name="user[username]">
  <label for="user_password">password</label>
  <input type="password" id="user_password" name="user[password]">
  <button>Sign up</button>
</form>

app/views/users/show.html.erb
<h1>Welcome <%= @user.username %></h1>
<p>
  <% @user.goals.try(:each) do |goal| %>
    <% next if current_user.id != goal.user_id && goal.private_goal %>
      <a href="<%= goal_url(goal) %>"><%= goal.title %></a>
      <%= goal.private_goal ? "Private" : "Public" %><br>
  <% end %>
</p>

<%= render "comments/form", subject: @user %><br>
<% @user.comments.try(:each) do |comment| %>
  <%= comment.body %>
<% end %>